create TABLE USER (
ID INTEGER NOT NULL,
USERNAME VARCHAR(256) NOT NULL,
PASSWORD VARCHAR(256) NOT NULL,
ROLE VARCHAR(256),
);

ALTER TABLE USER ADD CONSTRAINT USER_PK PRIMARY KEY ( ID );

CREATE TABLE PART (
ID INTEGER NOT NULL,
NAME VARCHAR(256) NOT NULL,
VALUE DECIMAL(9,2) NOT NULL,
QUANTITY INTEGER NOT NULL);

ALTER TABLE PART ADD CONSTRAINT PART_PK PRIMARY KEY ( ID );

CREATE TABLE "ORDER" (
ID INTEGER NOT NULL,
PARTS INTEGER NOT NULL,
"DATE" DATE NOT NULL);

ALTER TABLE "ORDER" ADD CONSTRAINT ORDER_PK PRIMARY KEY ( ID );

CREATE TABLE PERSON (
    ID         INTEGER NOT NULL,
    EMAIL      NVARCHAR2(256) NOT NULL,
    PASSWORD   NVARCHAR2(256) NOT NULL,
    ORDERS       INTEGER NOT NULL
);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY ( ID);

ALTER TABLE "ORDER" ADD CONSTRAINT ORDER_PARTS_FK FOREIGN KEY ( PARTS )  REFERENCES PART ( ID );

ALTER TABLE PERSON ADD CONSTRAINT PERSON_ORDERS_FK FOREIGN KEY (ORDERS) REFERENCES "ORDER"(ID);