INSERT INTO USER(ID, USERNAME, PASSWORD, ROLE) VALUES (3, 'admin', 'admin', 'admin');
INSERT INTO PART(ID, "NAME", "VALUE", "QUANTITY") VALUES (1, 'PART1', 20.25, 11);
INSERT INTO "ORDER"(ID, PARTS, "DATE") VALUES (1, 1, '2017-10-10');
INSERT INTO PERSON(ID, EMAIL, PASSWORD, ORDERS) VALUES (1, '1234QWER', '1QAZ2WSX', 1);